### ISSUE TITLE
Заглушки для документ сервиса

### ISSUE THREAD

**Issue by AlIld** [ITIS-MICROSERVICES-2021/DocumentService#5]
> Заглушки для документ сервиса и юзер сервиса; 26 минута на записи. 

В Юзер сервис создать в корне проекта папку фейк, положить 2 json с фейковыми ответами на запросы от поиск коллеги на замену и получение информации о сотруднике. Возвращать должен в редис. Находить по id запрос и по запросу класть соответствующую информацию. 
Все входящие запросы должны быть в виде контроллера, пока у нас нет очередей.

**В Документ сервис** тоже создать папку и положить jsonы с фейковыми ответами на запросы.
Заливать сюда - https://github.com/ITIS-MICROSERVICES-2021/UserService
https://github.com/ITIS-MICROSERVICES-2021/DocumentService

**Comment by azinit** [comment]
Со слов @Kochedykov-Alexander - DocumentService уже умеет возвращать документы/заглушки
